version: "3"

services:
  tyba-api:
    build: ./src
    hostname: tyba-api
    container_name: tyba-api
    restart: always
    ports:
      - 4000:4000
    volumes:
    - ./src:/src
    - /src/node_modules
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  mongo:
      image: mongo:latest
      container_name: mongo
      ports:
        - 27017:27017
      volumes:
        - mongo-data:/data/db
        - mongo-config:/data/configdb
volumes:
  redis-data:
  mongo-data:
  mongo-config: